default_platform(:android)

platform :android do
  desc "Submit a new Version to Internal Testing"
  lane :internal do
    begin
      #not need when using github actions since we already bundle on workflow 
      gradle(task: "clean")
      sh("flutter","build","appbundle")
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"],
      )
    rescue => exception
      raise exception unless exception.message.include?('APK specifies a version code that has already been used.')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
  lane :beta do
    begin
      #not need when using github actions since we already bundle on workflow 
      gradle(task: "clean")
      sh("flutter","build","appbundle")
      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"],
      )
    rescue => exception
      raise exception unless exception.message.include?('APK specifies a version code that has already been used.')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end